version: '3'
services:
  easybot:
    build:
      context: ./ntqq
      dockerfile: Dockerfile
    container_name: easybot
    environment:
      - ACCOUNT=3327481674 # 机器人qq
      - WS_ENABLE=true # 正向 WS
      - TOKEN=1234 # access_token，可以为空
      - WEBUI_TOKEN=wscc # 登录密钥，默认是自动生成的随机登录密码
      - WEB_HOST=http://0.0.0.0:5000
    restart: always
    volumes:
      - ./napcat/config:/app/napcat/config
      - ./ntqqi/qq:/root/.config/QQ
      - ./EasyBot:/data

networks:
  priv_net:
    #enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.31.0/24
          gateway: 192.168.31.1
          # ip_range: 192.168.5.6/32
          #- subnet: fd12:41:e237:6905::/64
          #  gateway: fd12:41:e237:6905::11
